Milestone 5: Event handlers
nicolasmarino99/react-calculator pull request #7
Opened 2020-07-31 20:25 UTC by nicolasmarino99

### In this Milestone we did:

- A click handler and state to App
- A click handler for each button
- Change button to class structure for receiving props
- Add logic to each calculate button
- Fix linter errors

2020-08-03 07:34 UTC, Oghenebrume50 requested changes
### CHANGES REQUIRED

Hi @nicolasmarino99 awesome work done so far :+1: I have commented on some things that can be worked on below, but just to emphasize

- Use functional component if a component has no state. 
- Work on handling the percentage operator, it currently returns an error. 

- To deal with some of the linter errors, use de-structuring where possible

please make changes and request for another review :slightly_smiling_face: 

**RAPHAEL NORIODE** :mask: stay_safe

2020-08-03 07:34 UTC, Oghenebrume50 commented on src/components/Button.js
> +class Button extends Component {
Components like this that do not have state should not be a class component, make them class components

2020-08-03 07:34 UTC, Oghenebrume50 commented on src/logic/operate.js
> +      return num1.mod(num2).toString();
this shoud be the percentage of the num1 only, 
![see this](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone4/performOperate.png) 
so basically num1 / 100 should work perfectly

2020-08-05 03:11 UTC, jofer86 approved these changes
## :wave: :wave: Hello!, I'm Jorge, and  I'm here to review this Pull Request, let's take a look shall we :eye: :eye: :eye: 
- Changes marked as **[OPTIONAL]** are not hard requirements but are nice to have.
- All of the required changes were met!!
## `const STATUS = 'Approved'` 🚀 🚀 🚀
--------------------------------------------------------------------
Cheers, 
Jorge Fernando Rincón Figueroa.
Technical Support Engineer.
**Slack: @jofer86**

2020-08-05 14:07 UTC, merged